name: cerdastani
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  cached_network_image: ^3.4.0
  shimmer: ^3.0.0
  bloc: ^8.1.4
  equatable: ^2.0.7
  dartz: ^0.10.1
  image_picker: ^1.0.7
  iconsax: ^0.0.8
  carousel_slider: ^5.0.0
  http: ^1.1.0
  intl: ^0.18.1

  # Firebase
  firebase_core: ^3.9.0
  google_sign_in: ^6.1.6
  firebase_storage: ^12.3.7
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.3.4
  url_launcher: ^6.1.12
  #state management
  get: ^4.6.5
  get_storage: ^2.1.1
  connectivity_plus: ^5.0.1
  logger: ^2.5.0
  flutter_native_splash: ^2.3.2
  get_it: ^8.0.3
  go_router: ^14.8.0
  dio: ^5.8.0+1
  flutter_dotenv: ^5.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0



flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/lottie/
    - assets/images/animations/
    - assets/logos/
    - assets/env/.env_dev

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
